package com.stayplugged.dailyca.bank;

import com.stayplugged.dailyca.model.GearProfile;
import java.util.Set;
import net.runelite.api.gameval.ItemID;

public final class BankGearClassifier
{
	public GearProfile classify(Set<Integer> itemIds)
	{
		int melee = 0;
		if (containsAny(itemIds, ItemID.ABYSSAL_WHIP, ItemID.ABYSSAL_WHIP_LAVA,
			ItemID.ABYSSAL_WHIP_ICE, ItemID.ZOMBIE_AXE))
		{
			melee = 2;
		}
		if (containsAny(itemIds, ItemID.OSMUMTENS_FANG, ItemID.OSMUMTENS_FANG_ORNAMENT,
			ItemID.BLADE_OF_SAELDOR, ItemID.BLADE_OF_SAELDOR_INACTIVE,
			ItemID.BLADE_OF_SAELDOR_INFINITE,
			ItemID.BLADE_OF_SAELDOR_INFINITE_ITHELL, ItemID.BLADE_OF_SAELDOR_INFINITE_IORWERTH,
			ItemID.BLADE_OF_SAELDOR_INFINITE_TRAHAEARN, ItemID.BLADE_OF_SAELDOR_INFINITE_CADARN,
			ItemID.BLADE_OF_SAELDOR_INFINITE_CRWYS, ItemID.BLADE_OF_SAELDOR_INFINITE_MEILYR,
			ItemID.BLADE_OF_SAELDOR_INFINITE_AMLODD))
		{
			melee = Math.max(melee, 3);
		}
		if (containsAny(itemIds, ItemID.SOULREAPER, ItemID.SOULREAPER_AXE_ORN,
			ItemID.SCYTHE_OF_VITUR, ItemID.SCYTHE_OF_VITUR_UNCHARGED,
			ItemID.SCYTHE_OF_VITUR_OR, ItemID.SCYTHE_OF_VITUR_UNCHARGED_OR,
			ItemID.SCYTHE_OF_VITUR_BL, ItemID.SCYTHE_OF_VITUR_UNCHARGED_BL))
		{
			melee = 4;
		}

		int ranged = 0;
		if (containsAny(itemIds, ItemID.TOXIC_BLOWPIPE, ItemID.TOXIC_BLOWPIPE_LOADED,
			ItemID.TOXIC_BLOWPIPE_ORNAMENT, ItemID.TOXIC_BLOWPIPE_LOADED_ORNAMENT))
		{
			ranged = 3;
		}
		if (hasBowfa(itemIds))
		{
			ranged = 3;
		}
		if (itemIds.contains(ItemID.TWISTED_BOW)
			|| (hasBowfa(itemIds) && hasCrystalBody(itemIds) && hasCrystalLegs(itemIds)))
		{
			ranged = 4;
		}

		int magic = 0;
		if (containsAny(itemIds, ItemID.TOTS, ItemID.TOTS_CHARGED, ItemID.TOTS_UNCHARGED,
			ItemID.TOTS_I_CHARGED, ItemID.TOTS_I_UNCHARGED,
			ItemID.TOXIC_TOTS_CHARGED, ItemID.TOXIC_TOTS_UNCHARGED,
			ItemID.TOXIC_TOTS_I_CHARGED, ItemID.TOXIC_TOTS_I_UNCHARGED,
			ItemID.TOXIC_TOTS_CHARGED_ORN, ItemID.TOXIC_TOTS_UNCHARGED_ORN,
			ItemID.TOXIC_TOTS_I_CHARGED_ORN, ItemID.TOXIC_TOTS_I_UNCHARGED_ORN,
			ItemID.TOTS_CHARGED_ORN, ItemID.TOTS_UNCHARGED_ORN, ItemID.TOTS_ORN,
			ItemID.TOTS_I_CHARGED_ORN, ItemID.TOTS_I_UNCHARGED_ORN))
		{
			magic = 2;
		}
		if (containsAny(itemIds, ItemID.SANGUINESTI_STAFF, ItemID.SANGUINESTI_STAFF_UNCHARGED,
			ItemID.SANGUINESTI_STAFF_OR, ItemID.SANGUINESTI_STAFF_UNCHARGED_OR))
		{
			magic = 3;
		}
		if (containsAny(itemIds, ItemID.TUMEKENS_SHADOW, ItemID.TUMEKENS_SHADOW_UNCHARGED))
		{
			magic = 4;
		}

		return new GearProfile(melee, ranged, magic, true);
	}

	private static boolean hasBowfa(Set<Integer> itemIds)
	{
		return containsAny(itemIds, ItemID.BOW_OF_FAERDHINEN, ItemID.BOW_OF_FAERDHINEN_INACTIVE,
			ItemID.BOW_OF_FAERDHINEN_INFINITE,
			ItemID.BOW_OF_FAERDHINEN_INFINITE_ITHELL, ItemID.BOW_OF_FAERDHINEN_INFINITE_IORWERTH,
			ItemID.BOW_OF_FAERDHINEN_INFINITE_TRAHAEARN, ItemID.BOW_OF_FAERDHINEN_INFINITE_CADARN,
			ItemID.BOW_OF_FAERDHINEN_INFINITE_CRWYS, ItemID.BOW_OF_FAERDHINEN_INFINITE_MEILYR,
			ItemID.BOW_OF_FAERDHINEN_INFINITE_AMLODD);
	}

	private static boolean hasCrystalBody(Set<Integer> itemIds)
	{
		return containsAny(itemIds, ItemID.CRYSTAL_CHESTPLATE, ItemID.CRYSTAL_CHESTPLATE_INACTIVE,
			ItemID.CRYSTAL_CHESTPLATE_HEFIN, ItemID.CRYSTAL_CHESTPLATE_INACTIVE_HEFIN,
			ItemID.CRYSTAL_CHESTPLATE_ITHELL, ItemID.CRYSTAL_CHESTPLATE_INACTIVE_ITHELL,
			ItemID.CRYSTAL_CHESTPLATE_IORWERTH, ItemID.CRYSTAL_CHESTPLATE_INACTIVE_IORWERTH,
			ItemID.CRYSTAL_CHESTPLATE_TRAHAEARN, ItemID.CRYSTAL_CHESTPLATE_INACTIVE_TRAHAEARN,
			ItemID.CRYSTAL_CHESTPLATE_CADARN, ItemID.CRYSTAL_CHESTPLATE_INACTIVE_CADARN,
			ItemID.CRYSTAL_CHESTPLATE_CRWYS, ItemID.CRYSTAL_CHESTPLATE_INACTIVE_CRWYS,
			ItemID.CRYSTAL_CHESTPLATE_AMLODD, ItemID.CRYSTAL_CHESTPLATE_INACTIVE_AMLODD);
	}

	private static boolean hasCrystalLegs(Set<Integer> itemIds)
	{
		return containsAny(itemIds, ItemID.CRYSTAL_PLATELEGS, ItemID.CRYSTAL_PLATELEGS_INACTIVE,
			ItemID.CRYSTAL_PLATELEGS_HEFIN, ItemID.CRYSTAL_PLATELEGS_INACTIVE_HEFIN,
			ItemID.CRYSTAL_PLATELEGS_ITHELL, ItemID.CRYSTAL_PLATELEGS_INACTIVE_ITHELL,
			ItemID.CRYSTAL_PLATELEGS_IORWERTH, ItemID.CRYSTAL_PLATELEGS_INACTIVE_IORWERTH,
			ItemID.CRYSTAL_PLATELEGS_TRAHAEARN, ItemID.CRYSTAL_PLATELEGS_INACTIVE_TRAHAEARN,
			ItemID.CRYSTAL_PLATELEGS_CADARN, ItemID.CRYSTAL_PLATELEGS_INACTIVE_CADARN,
			ItemID.CRYSTAL_PLATELEGS_CRWYS, ItemID.CRYSTAL_PLATELEGS_INACTIVE_CRWYS,
			ItemID.CRYSTAL_PLATELEGS_AMLODD, ItemID.CRYSTAL_PLATELEGS_INACTIVE_AMLODD);
	}

	private static boolean containsAny(Set<Integer> itemIds, int... candidates)
	{
		for (int candidate : candidates)
		{
			if (itemIds.contains(candidate))
			{
				return true;
			}
		}
		return false;
	}
}
